### ISSUE TITLE
sqlite-win32-x64.exe stays open

### ISSUE THREAD

**Issue by LPwithPaul** [tmotagam/sqlite-electron#11]
Short summary

Sometimes after closing the electron app, the sqlite-win32-x64.exe stays in Taskmanager and hogs performance.

Steps to reproduce

Create an electron app with a connection to an sqlite DB
Start the app using `electron .`
Quit it using control + C in the terminal.
See sqlite-win32-x64.exe in taskmanager

Additional Context

Lib version: 2.2.5
OS: Windows 10
Electron version: 22.0.0
Node version: v18.12.1

**Comment by tmotagam** [comment]
@LPwithPaul,
 Yes, I am working on removing the bug hopefully I will resolve in next update.

**Comment by ferminc** [comment]
Any updates on this?
