### ISSUE TITLE
Why fetching methods return boolean

### ISSUE THREAD

**Issue by mrAbra** [tmotagam/sqlite-electron#26]
``    ipcMain.handle('test-row', async () => {
        dataBase.insertRow("123", "deveui", "joineui");
        dataBase.insertRow("124", "deveui", "joineui");
        dataBase.insertRow("125", "deveui", "joineui");
        const result = await dataBase.read5Rows();
        console.log(result);
    });
.....
  async read5Rows() {
    try {
        const query = `
          SELECT * 
          FROM DeviceTable 
          ORDER BY time DESC 
          LIMIT 5
        `;
        const size = 5; 
        return await fetchMany(query, size);
      } catch (error) {
        console.error(error);
        return [];
      }
  }

``
why fetchMany returning true? btw i create needed data in db with executeQuery. I cheked it with db reader.

**Comment by tmotagam** [comment]
@mrAbra,
 Hi I checked it and it is not returning Boolean you can also put your dB in the example that is in this repo and see it it will return the data correctly I suggest checking your code.

**Comment by reprobate-music** [comment]
I have the same problem, but it doesn't always show up.

**Comment by davidaik** [comment]
`fetchAll` is returning `true` for me too.
