### ISSUE TITLE
Set dbpath without ipc

### ISSUE THREAD

**Issue by wiryonolau** [tmotagam/sqlite-electron#27]
Hi is possible to set dbpath without ipc or async 

I see the example that this need to be define multiple time, correct me if I'm wrong.

Usually we will init database first such as set path, checking schema or update table in the main before rendering window.

**Comment by tmotagam** [comment]
Hi @wiryonolau,
 No it is not possible to set dbPath without async as the command goes to python to open or create (In case it does not exists) the db.
The library only open one db at a time if have previously opened another db that db will be closed so that the new db can be opened.
