### ISSUE TITLE
大佬，请教一下版本和typeorm的问题

### ISSUE THREAD

**Issue by renjietan** [tmotagam/sqlite-electron#32]
1、您这个包 可以使用typeorm吗
2、您这个最新的包需要哪个版本的 node、node-gyp、node-pre-gyp、window-build-tools、electron、electron-builder、electron-rebuild  这些包

**Comment by tmotagam** [comment]
Hi @renjietan,
1. No you cannot use typeorm with this package.
2. No tools are required for running this package.
