### ISSUE TITLE
Error: 'str' object has no attribute sqlite-electron

### ISSUE THREAD

**Issue by Dmene** [tmotagam/sqlite-electron#7]
this is my code

`return await sqlite.executeMany('SELECT idTercero FROM clientes;')`

return error

`Error: 'str' object has no attribute sqlite-electorn`

**Comment by tmotagam** [comment]
@Dmene,
 Sorry to say you have made two mistakes.
1. executeMany cannot execute SELECT statements only executeQuery can do that.
2.  you have imported the library with a typo mistake it is sqlite-electron not sqlite-electorn

**Comment by Dmene** [comment]
i reviewed my package, is ok 
`"sqlite-electron": "^2.0.5"`
any method throws the same error

**Methods**
`executeQuery`
`executeMany`
`executeScript`

**Error**
`Error: 'str' object has no attribute 'execute'`
