### ISSUE TITLE
bug: setDbPath on missing file doesn't create a new database file

### ISSUE THREAD

**Issue by Supamiu** [tmotagam/sqlite-electron#9]
**Short summary**

When calling setDbPath on a path that is not already a sqlite db file, the promise is rejected.

**Steps to reproduce**

 - Create an electron app with just a call to `sqlite.setDbPath()` and give it a path that does exist except the final file (example: `sqlite.setDbPath("./database.db")`;
 - Start the app
 - It fails with error `UnhandledPromiseRejectionWarning: Error: unable to open database file`

**Additional Context**

**Lib version**: 2.2.5
**OS**: Windows 10
**Electron version**: 21.1.1
**Node version**: 16.13.2

**Investigation**

Checking https://github.com/tmotagam/sqlite-electron/blob/master/sqlite.py#L24-L39 makes me think this case is not handled, by checking the example documentation in README.md I expected it to create the db file for me (doc says "This is a function for opening a existing database or creating a new database for operation.").

If that's not the goal of this function, it might be worth creating a new function exposed by the API to create a database file if it's missing.

**Comment by tmotagam** [comment]
Hello @Supamiu,
 The setDbPath function is working properly with or without the existence of the file.

**Comment by Supamiu** [comment]
Do you mean it creates the file? Because my steps to reproduce do not create the file on my system, what could be wrong then?

**Comment by tmotagam** [comment]
@Supamiu,
Please recheck your code.

**Comment by Supamiu** [comment]
Alright, so.

Just to make sure this was easy to reproduce, I decided to make minimal steps to reproduce, to check if the file was created or not.

Here are my steps to reproduce:

- Create a dummy project with npm init in an empty directory
- Run `npm install --save sqlite-electron`
- Create an index.js file, with the content that's shown below
- Run `node index.js`
- You get the following error instead of having a file created like README.md says:

    > [UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Error: unable to open database file".] {
  code: 'ERR_UNHANDLED_REJECTION'
} Uncaught Exception thrown

Here is the code for the index.js test:

```js
const sqlite = require('sqlite-electron');
const path = require('path');

(async () => {
    await sqlite.setdbPath(path.join(__dirname, './test.db'));
    console.log('DONE');
})()
```

I checked my code, it's just what's given in the readme, and the file is not created.

**Comment by tmotagam** [comment]
@Supamiu,
Run this code it is working and the code you wrote wont work because the library is actually creating an absolute path for itself just use relative paths and hope everything will be fine.

```javascript
const sqlite = require('sqlite-electron');
const path = require('path');

(async () => {
    await sqlite.setdbPath('./testfolder/test.db');
    console.log('DONE');
})()
```

**Comment by Supamiu** [comment]
Hm, using relative path is not something you'd want for electron production env tbh, as it can be in various places and you'll want the db to always be at the same spot. What's the reason for it to not work with absolute path?

I feel like I'll switch to just node's sqlite3 anyways, but figured I should at least help by reporting this so anyone stumbling on this issue will know what's going on 😃

**Comment by bradzoob** [comment]
Ah yes i just ran into this, thanks @Supamiu .
